from .FaceDepthNode import NODE_CLASS_MAPPINGS as FACE_DEPTH_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FACE_DEPTH_NAMES

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(FACE_DEPTH_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(FACE_DEPTH_NAMES)


__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
